---
downloads: ~/.ansible-downloads/

configure_dotfiles: no 
configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - git
  - nvm
  - mysql
  - tig
  - tmux
  - fzf
  - knqyf263/pet/pet
  - z

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - caskroom/fonts
#  - homebrew/php

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - dropbox
  - google-chrome
  - slack
  - sublime-text
  - vagrant
  - virtualbox
  - evernote
  - workflowy
  - spectacle
  - phpstorm
  - datagrip
  - visual-studio-code
  - cheatsheet
  - karabiner-elements
  - zoomus 
  - iterm2
  - font-meslo-for-powerline
  - toggl
  - meld
  - anki
  - phoenix

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages:
  #- name: compass
  #- state: latest
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
